from setuptools import setup
from os.path import dirname
from glob import glob

# Package list is autogenerated to be any 'zpg' subfolder containing a __init__.py file
package_list = [dirname(p).replace('\\', '.') for p in glob('zpgenerator/**/__init__.py', recursive=True)]

setup(
    name='zpgenerator',
    author="quandela",
    version='0.2.0',
    packages=package_list,
    install_requires=[
        'qutip',
        'numpy',
        'scipy',
        'frozendict',
        'matplotlib'
    ],
    extras_require={
        'interactive': ['jupyter'],
    }
)